const LOGIN = {
  START: "LOGIN_START",
  SUCCESS: "LOGIN_SUCCESS",
  FAIL: "LOGOUT"
};

const REGISTER = {
  START: "REGISTER_START",
  SUCCESS: "REGISTER_SUCCESS"
};

const LOAD = {
  START: "LOAD_START",
  SUCCESS: "LOAD_SUCCESS",
  FAIL: "LOAD_FAIL"
};

const ASK = {
  START: "ASK_START",
  SUCCESS: "ASK_SUCCESS",
  FAIL: "ASK_FAIL"
}

export { LOGIN, REGISTER, LOAD, ASK };
